### ISSUE TITLE
AI integration

### ISSUE THREAD

**Issue by danloh** [mdSilo/mdSilo-app#439]

**Comment by amiyatulu** [comment]
Will AI integration lead privacy issues and allow data to move to server?

**Comment by johnblommers** [comment]
> Will AI integration lead privacy issues and allow data to move to server?

All of the prompt text is sent to the server. While the communications with the server likely is encrypted in flight, the server will decrypt it in order to process the prompt text. Anything can happen at the server end. Agents Smith and Johnson may be sitting  there watching your data go by. You don't know what really goes on in those data centers, or even where that data center is.

Therefore you should never send confidential, protected, sensitive etc information to an AI.

**Comment by danloh** [comment]
closing it as won't do soon
